# adapted from https://github.com/catch22/octave-doctest/blob/master/.travis.yml
sudo: required
dist: trusty
language: generic
matrix:
  include:
    - env: OCT_PPA=no
      addons:
        apt:
          packages:
            - octave
            - liboctave-dev
install:
  - git clone https://github.com/MOxUnit/MOxUnit.git
  - cd MOxUnit
  - make install
script: ./run_tests.sh
